version: '2'
services:
  mongodb:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongo_data:/data/db
  hooker_scrapper:
    build: hooker_scrapper/
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_NAME=hooker_map
    depends_on:
      - mongodb
volumes:
  mongo_data: